// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Trike Speedo

#include "ui.h"
#include "ui_helpers.h"

// SCREEN: ui_screen
void ui_screen_init(void);
lv_obj_t *ui_screen;
lv_obj_t *ui_speed;
lv_obj_t *ui_kmh;
lv_obj_t *ui_time;
lv_obj_t *ui_icon;
lv_obj_t *ui_sats;
lv_obj_t *ui____initial_actions0;


///////////////////// SCREENS ////////////////////
void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_screen);
}
