// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Trike Speedo

#ifndef TRIKE_SPEEDO_UI_H
#define TRIKE_SPEEDO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_screen
void ui_screen_init(void);
extern lv_obj_t *ui_screen;
extern lv_obj_t *ui_speed;
extern lv_obj_t *ui_kmh;
extern lv_obj_t *ui_time;
extern lv_obj_t *ui_icon;
extern lv_obj_t *ui_sats;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE(ui_img_satellite_png); // assets\satellite.png

LV_FONT_DECLARE(ui_font_SpaceGroteskMedium24);
LV_FONT_DECLARE(ui_font_SpaceGroteskMedium56);
LV_FONT_DECLARE(ui_font_SpaceGroteskMedium88);
LV_FONT_DECLARE(ui_font_SpaceGroteskMedium96);
LV_FONT_DECLARE(ui_font_SpaceGroteskMedium42);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
