// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Trike Speedo

#include "../ui.h"

void ui_screen_init(void)
{
    ui_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_speed = lv_label_create(ui_screen);
    lv_obj_set_width(ui_speed, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_speed, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_speed, -75);
    lv_obj_set_y(ui_speed, -35);
    lv_obj_set_align(ui_speed, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_text_align(ui_speed, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_speed, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speed, &ui_font_SpaceGroteskMedium88, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kmh = lv_label_create(ui_screen);
    lv_obj_set_width(ui_kmh, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_kmh, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_kmh, 250);
    lv_obj_set_y(ui_kmh, -85);
    lv_obj_set_align(ui_kmh, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_kmh, "km/h");
    lv_obj_set_style_text_color(ui_kmh, lv_color_hex(0xA9A9A9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kmh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kmh, &ui_font_SpaceGroteskMedium24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_screen);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_time, 0);
    lv_obj_set_y(ui_time, 40);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &ui_font_SpaceGroteskMedium56, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon = lv_img_create(ui_screen);
    lv_img_set_src(ui_icon, &ui_img_satellite_png);
    lv_obj_set_width(ui_icon, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_icon, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_icon, 100);
    lv_obj_set_y(ui_icon, -50);
    lv_obj_set_align(ui_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_icon, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_icon, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_sats = lv_label_create(ui_screen);
    lv_obj_set_width(ui_sats, 32);
    lv_obj_set_height(ui_sats, 38);
    lv_obj_set_x(ui_sats, 135);
    lv_obj_set_y(ui_sats, -49);
    lv_obj_set_align(ui_sats, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_sats, lv_color_hex(0xA9A9A9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sats, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_sats, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sats, &ui_font_SpaceGroteskMedium42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_sats, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_sats, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_sats, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_sats, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
}
